spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/appointments
    username: appointments
    password: 0513Appointments-prod
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
