server:
  port: 7777

spring:
  profiles:
    active: default
  application:
    name: config-server

  # Aggressive exclusion of metrics and actuator
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.observation.ObservationAutoConfiguration

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
      server:
        git:
          uri: https://github.com/celotts/microservice-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          clone-on-start: true
          timeout: 10

# Completely disable actuator
management:
  endpoints:
    enabled-by-default: false
  metrics:
    enable:
      all: false
  health:
    defaults:
      enabled: false

# Disable system metrics
system:
  metrics:
    enabled: false

# Logging configuration
logging:
  level:
    root: WARN
    org.springframework: WARN