server:
  port: 7777

spring:
  profiles:
    active: default
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/celotts/microservice-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          clone-on-start: true
          timeout: 10  # ⏳ Asegura que no haya tiempo de espera demasiado corto

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}  # 📍 Usa el nombre de host adecuado
    instance-id: "${spring.application.name}:${random.value}:${server.port}"
  client:
    registry-fetch-interval-seconds: 10  # Espera 10 segundos antes de buscar instancias
    initial-instance-info-replication-interval-seconds: 10  # Evita la auto-registración instantánea
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://registry-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,configprops"
  health:
    show-details: always
  server:
    port: 7778  # 💡 Separado del puerto principal para evitar conflictos

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG